version: "2.19"     # Docker Compose version
services:           # The containers that we want to deploy
  
  insecure_webapp:  # name of the container
    build:
      context: .    # defines either a path to a directory containing a Dockerfile, or a URL to a git repository
      dockerfile: php-image/dockerfile  # relative path from the context to a directory containing the dockerfile
    ports:
      - "8000:80"   # Mapping port 8000 on our machine to access port 80 on the container
    depends_on:
      - insecure_database               # Makes it wait for the database container to start before running
    volumes:
      - ./insecure_websafe:/var/www/html
    networks:
      internal_insecure:
        ipv4_address: "192.168.20.69"

  insecure_database: 
    image: mysql:latest
    environment:
      - MYSQL-DATABASE=websafe
      - MYSQL_ROOT_PASSWORD=w3bs@fe_ADmin 
      - MYSQL_USER=Lottie
      - MYSQL_PASSWORD=Ad0r@ble
    restart: unless-stopped
    volumes:
      # - ./insecure_database/mysql:/var/lib/mysql # UNCOMMENT THIS LINE TO MAKE DATABASE PERSISTENT
      - ./insecure_database/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - internal_insecure

  insecure_phpmyadmin:
    image: phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_ARBITRARY=1 
      - PMA_HOST=insecure_database
      - PMA_PORT=3306
      # - PMA_USER=root                 # UNCOMMENT THESE LINES TO AUTOMATICALLY LOG IN TO DATABASE
      # - PMA_PASSWORD=w3bs@fe_ADmin    # UNCOMMENT THESE LINES TO AUTOMATICALLY LOG IN TO DATABASE
    networks:
      - internal_insecure

  insecure_server1:
    build:
      context: . 
      dockerfile: php-image/dockerfile
    ports:
      - "8002:80" 
    depends_on:
      - insecure_database 
    volumes:
      - ./insecure_server1:/var/www/html
    networks:
      internal_insecure:
        ipv4_address: "192.168.20.22"


  ##############################################################
  ##############################################################
  ##############################################################

  secure_webapp:
    build:
      context: .
      dockerfile: php-image/dockerfile
    ports:
      - "9000:80"
    depends_on:
      - secure_database
    volumes:
      - ./secure_websafe:/var/www/html
    networks:
      internal_secure:
        ipv4_address: "192.168.40.69"

  secure_database: 
    image: mysql:latest
    environment:
      - MYSQL-DATABASE=websafe
      - MYSQL_ROOT_PASSWORD=w3bs@fe_ADmin 
      - MYSQL_USER=Lottie
      - MYSQL_PASSWORD=Ad0r@ble
    restart: unless-stopped
    volumes:
      # - ./secure_database/mysql:/var/lib/mysql # UNCOMMENT THIS LINE TO MAKE DATABASE PERSISTENT
      - ./secure_database/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - internal_secure

  secure_phpmyadmin:
    image: phpmyadmin
    ports:
      - "9001:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=secure_database
      - PMA_PORT=3306
      # - PMA_USER=root                 # UNCOMMENT THESE LINES TO AUTOMATICALLY LOG IN TO DATABASE
      # - PMA_PASSWORD=w3bs@fe_ADmin    # UNCOMMENT THESE LINES TO AUTOMATICALLY LOG IN TO DATABASE
    networks:
      - internal_secure

  secure_server1: 
    build:
      context: . 
      dockerfile: php-image/dockerfile 
    ports:
      - "9002:80" 
    depends_on:
      - secure_database 
    volumes:
      - ./secure_server1:/var/www/html
    networks:
      internal_secure:
        ipv4_address: "192.168.40.22"

networks:
  internal_insecure:
    ipam: 
      driver: default
      config:
        - subnet: "192.168.20.0/24" 
  internal_secure:
    ipam: 
      driver: default
      config:
        - subnet: "192.168.40.0/24" 